---

   - name: Yum install Zabbix release in RHEL or CentOS
     yum: name=http://repo.zabbix.com/zabbix/{{ zabbix_version }}/rhel/{{ ansible_distribution_major_version }}/x86_64/zabbix-release-3.4-2.el{{ ansible_distribution_major_version }}.noarch.rpm
     when: ansible_os_family == "RedHat"
     tags: Zabbix-Agent

   - name: Yum install Zabbix agent
     yum: name=zabbix-agent
     when: ansible_os_family == "RedHat"
     tags: Zabbix-Agent
    
   - name: Ubuntu | Add Zabbix signing key
     apt_key:
       url: https://repo.zabbix.com/zabbix-official-repo.key
       state: present
     when: ansible_distribution == "Ubuntu"
     tags: Zabbix-Agent

   - name: Ubuntu | Installing Zabbix deb-src repository 
     apt_repository:
       repo: deb http://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu/ {{ ansible_distribution_release }} main
       state: present
       filename: zabbix
     when: ansible_distribution == "Ubuntu"
     tags: Zabbix-Agent

   - name: Ubuntu | Installing zabbix-agent
     apt:
       name: zabbix-agent
       state: present
       update_cache: yes
     when: ansible_distribution == "Ubuntu"
     tags: Zabbix-Agent 

   - name: Yum install policycoreutils-python
     yum: 
       name: policycoreutils-python
       state: installed
     when: ansible_os_family == "RedHat"
     tags: Selinux
     
   - name: Allow zabbix_agent to start (SELinux)
     selinux_permissive:
       name: zabbix_agent_t
       permissive: true
     when: ansible_os_family == "RedHat" 
     tags: Selinux
     
   - name: Enable service zabbix-agent
     service:
       name: zabbix-agent
       enabled: yes
tags: Zabbix-Agent
